### ISSUE TITLE
Ability to mark FAQ sets and individual items as inactive

### ISSUE THREAD

**Issue by Mark-H** [josht/faqMan#33]
Sometimes you want to hide a certain FAQ set or an individual FAQ item, but you don't want to remove it completely, just want them hidden from a list of FAQs for now.

For example on the modmore site we have a FAQ overview page that shows all the sets so you can browse them easily. That also includes a set about the MODX weekend, which happened last year so isn't really relevant anymore, and it could also show FAQ sets that aren't supposed to be accessible yet (e.g. FAQs for an unreleased product). An active or hidden flag on sets and items would make it possible to manage that better.

**Comment by Mark-H** [comment]
Hi @josht! Glad to see this made it in :)

It appears though there's a slight bug in the faqManSets snippet, these lines:

```` php
 if (!empty($set)) {
    $field = (is_numeric($set)) ? 'id' : 'name';
    $c->where(array(
        $field => $set,
    ));

    // Hide unpublished sets
    if (!$showUnpublished) {
        $c->where(array('published' => true));
    }
}
````

Should probably be like this:
```` php
 if (!empty($set)) {
    $field = (is_numeric($set)) ? 'id' : 'name';
    $c->where(array(
        $field => $set,
    ));
}

// Hide unpublished sets
if (!$showUnpublished) {
    $c->where(array('published' => true));
}
````

Unless I'm missing something - what do you think?

**Comment by josht** [comment]
Hah, dangit! That's what I get for copy/pasting and not double checking.

I see a 1.2.1 coming later today.
