### ISSUE TITLE
'Description' contents is converted to number

### ISSUE THREAD

**Issue by Maef** [josht/faqMan#39]
We have this odd issue since upgrading to PHP7.2 (from 7.0)

'Update FAQ Set' on an entry sets the content to '0' after a save. When you enter a number it is correctly stored.

Our setup:

MODX Revolution 2.6.5-pl (traditional)
Database: 10.2.18-MariaDB
Database charset: utf8
PHP Version 7.2.10

**Comment by josht** [comment]
Yep, thanks, I missed that.

**Comment by josht** [comment]
Fixed in v1.3.0
