### ISSUE TITLE
Upgrade to 2 broke it

### ISSUE THREAD

**Issue by crewmark** [josht/faqMan#41]
I've just upgraded from 1.3 to 2 and it stopped working. I get a HTTP Error 500.

`mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /core/components/faqman/model/faqman/faqman.class.php on line 30, referer: http://XXXXXXXXXX/manager/?a=workspaces`

(Ive removed the site info as it's a site that hasn't been released yet.)

**Comment by josht** [comment]
@crewmark  What version of PHP are you on?

Also, you might try refreshing your site cache through the manager. It kind of seems like your upgrade may not have completely correctly.  If it still doesn't work, if might try reinstalling the extra.

**Comment by crewmark** [comment]
@josht I'm running ver 7.0.27

I cleared the cache, which I always do after any install or upgrade. I have uninstalled and reinstalled a few times via the Manager but had the same problem. I have uninstalled and preserved previous version and it 1.3 works again.

I initially installed FM 1.2.1 in Aug 2017 then updated to v 1.3 in Dec 2018. All good. It's just this latest that's come up with a completely blank page. The server errors are all the same as specified above.

**Comment by crewmark** [comment]
@josht I've totally deleted all versions of FAQ Manager, cleared all caches etc and reinstalled. I've made a very basic template and added `[[faqman]]`. I get the same error.

Seems to be an error establishing the constants for the type column in the database (well that's the line it's failing at). What version of MySQL do I need?

**Comment by josht** [comment]
@crewmark  Sorry it took so long, I found the fix for this. I goofed up and added some stuff only supported in  PHP 7.1 and up.  I'll get the new extra package built and uploaded later this evening.

**Comment by josht** [comment]
RC3 has been uploaded and released.
