### ISSUE TITLE
On MySQL 8, a `rank` field needs to be escaped

### ISSUE THREAD

**Issue by Mark-H** [josht/faqMan#44]
Without the special escaping, faq entries don't show up.

faqMan line 68 adding the `$modx->quote` call does the trick:

    $ci->sortby($modx->quote($sortBy), $sortDir);

Alternatively that could be applied only when sortBy is not `rank`.

**Comment by josht** [comment]
Thanks for letting me know. I should probably start including MySQL 8 when testing.

**Comment by Mark-H** [comment]
It's been out for a while (2018 IIRC) but database servers aren't quick to get updated in the wild. ;)

faqManSets snippet also needs similar fixes. Line 39 and 57.
